image: ubuntu:20.04

stages:
  - sign

sign:
  stage: sign
  script:
    - sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
    - apt update && apt install -y python3 python3-pip
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - echo "$HAIDAN_MULTI"
    - python3 main.py